1 fix vulnerability issue
nish-d/nish-d.github.io pull request #4
Opened 2020-10-08 16:41 UTC by chetangawai

#1 

Upgraded jquery to 3.5.1 and tested the application

2020-10-08 16:41 UTC, chetangawai commented
@nish-d Please review

2020-10-09 04:49 UTC, nish-d commented on Gemfile
> +gem 'kramdown-parser-gfm'
Please remove these changes.

2020-10-09 04:50 UTC, nish-d requested changes

2020-10-09 04:50 UTC, nish-d commented on Gemfile.lock
> +  remote: https://rubygems.org/
Please remove these changes.

2020-10-09 07:27 UTC, chetangawai commented on Gemfile.lock
> +  remote: https://rubygems.org/
Removed the commit

2020-10-09 07:27 UTC, chetangawai commented on Gemfile
> +gem 'kramdown-parser-gfm'
Removed the commit

2020-10-09 10:42 UTC, nish-d approved these changes
Thanks a lot @chetangawai for your PR!! Feel free to point out other issues and raise more PRs. 👍

2020-10-09 10:47 UTC, merged